/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FixtureFixtureIdRouteImport } from './routes/fixture/$fixtureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixtureFixtureIdRoute = FixtureFixtureIdRouteImport.update({
  id: '/fixture/$fixtureId',
  path: '/fixture/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixture/$fixtureId': typeof FixtureFixtureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixture/$fixtureId': typeof FixtureFixtureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fixture/$fixtureId': typeof FixtureFixtureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fixture/$fixtureId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fixture/$fixtureId'
  id: '__root__' | '/' | '/fixture/$fixtureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixtureFixtureIdRoute: typeof FixtureFixtureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixture/$fixtureId': {
      id: '/fixture/$fixtureId'
      path: '/fixture/$fixtureId'
      fullPath: '/fixture/$fixtureId'
      preLoaderRoute: typeof FixtureFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixtureFixtureIdRoute: FixtureFixtureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
